/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AAdditionalStatementInstruction extends PAdditionalStatementInstruction
{
    private TComma _comma_;
    private PStatementInstruction _statementInstruction_;

    public AAdditionalStatementInstruction()
    {
        // Constructor
    }

    public AAdditionalStatementInstruction(
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PStatementInstruction _statementInstruction_)
    {
        // Constructor
        setComma(_comma_);

        setStatementInstruction(_statementInstruction_);

    }

    @Override
    public Object clone()
    {
        return new AAdditionalStatementInstruction(
            cloneNode(this._comma_),
            cloneNode(this._statementInstruction_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAdditionalStatementInstruction(this);
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PStatementInstruction getStatementInstruction()
    {
        return this._statementInstruction_;
    }

    public void setStatementInstruction(PStatementInstruction node)
    {
        if(this._statementInstruction_ != null)
        {
            this._statementInstruction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._statementInstruction_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comma_)
            + toString(this._statementInstruction_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._statementInstruction_ == child)
        {
            this._statementInstruction_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._statementInstruction_ == oldChild)
        {
            setStatementInstruction((PStatementInstruction) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
