/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AAdditionalQuestionInstruction extends PAdditionalQuestionInstruction
{
    private TComma _comma_;
    private PQuestionInstruction _questionInstruction_;

    public AAdditionalQuestionInstruction()
    {
        // Constructor
    }

    public AAdditionalQuestionInstruction(
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PQuestionInstruction _questionInstruction_)
    {
        // Constructor
        setComma(_comma_);

        setQuestionInstruction(_questionInstruction_);

    }

    @Override
    public Object clone()
    {
        return new AAdditionalQuestionInstruction(
            cloneNode(this._comma_),
            cloneNode(this._questionInstruction_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAdditionalQuestionInstruction(this);
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PQuestionInstruction getQuestionInstruction()
    {
        return this._questionInstruction_;
    }

    public void setQuestionInstruction(PQuestionInstruction node)
    {
        if(this._questionInstruction_ != null)
        {
            this._questionInstruction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._questionInstruction_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comma_)
            + toString(this._questionInstruction_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._questionInstruction_ == child)
        {
            this._questionInstruction_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._questionInstruction_ == oldChild)
        {
            setQuestionInstruction((PQuestionInstruction) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
