/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import java.util.*;
import analysis.*;

@SuppressWarnings("nls")
public final class AAskInstructionList extends PAskInstructionList
{
    private PAskInstruction _askInstruction_;
    private final LinkedList<PAdditionalAskInstruction> _additionalAskInstruction_ = new LinkedList<PAdditionalAskInstruction>();
    private TSemicolon _semicolon_;

    public AAskInstructionList()
    {
        // Constructor
    }

    public AAskInstructionList(
        @SuppressWarnings("hiding") PAskInstruction _askInstruction_,
        @SuppressWarnings("hiding") List<?> _additionalAskInstruction_,
        @SuppressWarnings("hiding") TSemicolon _semicolon_)
    {
        // Constructor
        setAskInstruction(_askInstruction_);

        setAdditionalAskInstruction(_additionalAskInstruction_);

        setSemicolon(_semicolon_);

    }

    @Override
    public Object clone()
    {
        return new AAskInstructionList(
            cloneNode(this._askInstruction_),
            cloneList(this._additionalAskInstruction_),
            cloneNode(this._semicolon_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAskInstructionList(this);
    }

    public PAskInstruction getAskInstruction()
    {
        return this._askInstruction_;
    }

    public void setAskInstruction(PAskInstruction node)
    {
        if(this._askInstruction_ != null)
        {
            this._askInstruction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._askInstruction_ = node;
    }

    public LinkedList<PAdditionalAskInstruction> getAdditionalAskInstruction()
    {
        return this._additionalAskInstruction_;
    }

    public void setAdditionalAskInstruction(List<?> list)
    {
        for(PAdditionalAskInstruction e : this._additionalAskInstruction_)
        {
            e.parent(null);
        }
        this._additionalAskInstruction_.clear();

        for(Object obj_e : list)
        {
            PAdditionalAskInstruction e = (PAdditionalAskInstruction) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._additionalAskInstruction_.add(e);
        }
    }

    public TSemicolon getSemicolon()
    {
        return this._semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(this._semicolon_ != null)
        {
            this._semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semicolon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._askInstruction_)
            + toString(this._additionalAskInstruction_)
            + toString(this._semicolon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._askInstruction_ == child)
        {
            this._askInstruction_ = null;
            return;
        }

        if(this._additionalAskInstruction_.remove(child))
        {
            return;
        }

        if(this._semicolon_ == child)
        {
            this._semicolon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._askInstruction_ == oldChild)
        {
            setAskInstruction((PAskInstruction) newChild);
            return;
        }

        for(ListIterator<PAdditionalAskInstruction> i = this._additionalAskInstruction_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAdditionalAskInstruction) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
