/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AComparisonExpression extends PExpression
{
    private PComparison _comparison_;

    public AComparisonExpression()
    {
        // Constructor
    }

    public AComparisonExpression(
        @SuppressWarnings("hiding") PComparison _comparison_)
    {
        // Constructor
        setComparison(_comparison_);

    }

    @Override
    public Object clone()
    {
        return new AComparisonExpression(
            cloneNode(this._comparison_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComparisonExpression(this);
    }

    public PComparison getComparison()
    {
        return this._comparison_;
    }

    public void setComparison(PComparison node)
    {
        if(this._comparison_ != null)
        {
            this._comparison_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comparison_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comparison_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comparison_ == child)
        {
            this._comparison_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comparison_ == oldChild)
        {
            setComparison((PComparison) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
