/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AEqualToComparison extends PComparison
{
    private PComparison _comparison_;
    private TEqualTo _equalTo_;
    private PArithmetic _arithmetic_;

    public AEqualToComparison()
    {
        // Constructor
    }

    public AEqualToComparison(
        @SuppressWarnings("hiding") PComparison _comparison_,
        @SuppressWarnings("hiding") TEqualTo _equalTo_,
        @SuppressWarnings("hiding") PArithmetic _arithmetic_)
    {
        // Constructor
        setComparison(_comparison_);

        setEqualTo(_equalTo_);

        setArithmetic(_arithmetic_);

    }

    @Override
    public Object clone()
    {
        return new AEqualToComparison(
            cloneNode(this._comparison_),
            cloneNode(this._equalTo_),
            cloneNode(this._arithmetic_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEqualToComparison(this);
    }

    public PComparison getComparison()
    {
        return this._comparison_;
    }

    public void setComparison(PComparison node)
    {
        if(this._comparison_ != null)
        {
            this._comparison_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comparison_ = node;
    }

    public TEqualTo getEqualTo()
    {
        return this._equalTo_;
    }

    public void setEqualTo(TEqualTo node)
    {
        if(this._equalTo_ != null)
        {
            this._equalTo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._equalTo_ = node;
    }

    public PArithmetic getArithmetic()
    {
        return this._arithmetic_;
    }

    public void setArithmetic(PArithmetic node)
    {
        if(this._arithmetic_ != null)
        {
            this._arithmetic_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arithmetic_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comparison_)
            + toString(this._equalTo_)
            + toString(this._arithmetic_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comparison_ == child)
        {
            this._comparison_ = null;
            return;
        }

        if(this._equalTo_ == child)
        {
            this._equalTo_ = null;
            return;
        }

        if(this._arithmetic_ == child)
        {
            this._arithmetic_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comparison_ == oldChild)
        {
            setComparison((PComparison) newChild);
            return;
        }

        if(this._equalTo_ == oldChild)
        {
            setEqualTo((TEqualTo) newChild);
            return;
        }

        if(this._arithmetic_ == oldChild)
        {
            setArithmetic((PArithmetic) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
