/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AExpressionElementTerm extends PElementTerm
{
    private TLeftParenthesis _leftParenthesis_;
    private PElementExpression _elementExpression_;
    private TRightParenthesis _rightParenthesis_;

    public AExpressionElementTerm()
    {
        // Constructor
    }

    public AExpressionElementTerm(
        @SuppressWarnings("hiding") TLeftParenthesis _leftParenthesis_,
        @SuppressWarnings("hiding") PElementExpression _elementExpression_,
        @SuppressWarnings("hiding") TRightParenthesis _rightParenthesis_)
    {
        // Constructor
        setLeftParenthesis(_leftParenthesis_);

        setElementExpression(_elementExpression_);

        setRightParenthesis(_rightParenthesis_);

    }

    @Override
    public Object clone()
    {
        return new AExpressionElementTerm(
            cloneNode(this._leftParenthesis_),
            cloneNode(this._elementExpression_),
            cloneNode(this._rightParenthesis_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpressionElementTerm(this);
    }

    public TLeftParenthesis getLeftParenthesis()
    {
        return this._leftParenthesis_;
    }

    public void setLeftParenthesis(TLeftParenthesis node)
    {
        if(this._leftParenthesis_ != null)
        {
            this._leftParenthesis_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._leftParenthesis_ = node;
    }

    public PElementExpression getElementExpression()
    {
        return this._elementExpression_;
    }

    public void setElementExpression(PElementExpression node)
    {
        if(this._elementExpression_ != null)
        {
            this._elementExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._elementExpression_ = node;
    }

    public TRightParenthesis getRightParenthesis()
    {
        return this._rightParenthesis_;
    }

    public void setRightParenthesis(TRightParenthesis node)
    {
        if(this._rightParenthesis_ != null)
        {
            this._rightParenthesis_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rightParenthesis_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._leftParenthesis_)
            + toString(this._elementExpression_)
            + toString(this._rightParenthesis_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._leftParenthesis_ == child)
        {
            this._leftParenthesis_ = null;
            return;
        }

        if(this._elementExpression_ == child)
        {
            this._elementExpression_ = null;
            return;
        }

        if(this._rightParenthesis_ == child)
        {
            this._rightParenthesis_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._leftParenthesis_ == oldChild)
        {
            setLeftParenthesis((TLeftParenthesis) newChild);
            return;
        }

        if(this._elementExpression_ == oldChild)
        {
            setElementExpression((PElementExpression) newChild);
            return;
        }

        if(this._rightParenthesis_ == oldChild)
        {
            setRightParenthesis((TRightParenthesis) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
