/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AExpressionExpression extends PExpression
{
    private PElementExpression _elementExpression_;
    private TElementOf _elementOf_;
    private PSetExpression _setExpression_;

    public AExpressionExpression()
    {
        // Constructor
    }

    public AExpressionExpression(
        @SuppressWarnings("hiding") PElementExpression _elementExpression_,
        @SuppressWarnings("hiding") TElementOf _elementOf_,
        @SuppressWarnings("hiding") PSetExpression _setExpression_)
    {
        // Constructor
        setElementExpression(_elementExpression_);

        setElementOf(_elementOf_);

        setSetExpression(_setExpression_);

    }

    @Override
    public Object clone()
    {
        return new AExpressionExpression(
            cloneNode(this._elementExpression_),
            cloneNode(this._elementOf_),
            cloneNode(this._setExpression_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpressionExpression(this);
    }

    public PElementExpression getElementExpression()
    {
        return this._elementExpression_;
    }

    public void setElementExpression(PElementExpression node)
    {
        if(this._elementExpression_ != null)
        {
            this._elementExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._elementExpression_ = node;
    }

    public TElementOf getElementOf()
    {
        return this._elementOf_;
    }

    public void setElementOf(TElementOf node)
    {
        if(this._elementOf_ != null)
        {
            this._elementOf_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._elementOf_ = node;
    }

    public PSetExpression getSetExpression()
    {
        return this._setExpression_;
    }

    public void setSetExpression(PSetExpression node)
    {
        if(this._setExpression_ != null)
        {
            this._setExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._setExpression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._elementExpression_)
            + toString(this._elementOf_)
            + toString(this._setExpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._elementExpression_ == child)
        {
            this._elementExpression_ = null;
            return;
        }

        if(this._elementOf_ == child)
        {
            this._elementOf_ = null;
            return;
        }

        if(this._setExpression_ == child)
        {
            this._setExpression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._elementExpression_ == oldChild)
        {
            setElementExpression((PElementExpression) newChild);
            return;
        }

        if(this._elementOf_ == oldChild)
        {
            setElementOf((TElementOf) newChild);
            return;
        }

        if(this._setExpression_ == oldChild)
        {
            setSetExpression((PSetExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
