/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AForAllProposition extends PProposition
{
    private TForAll _forAll_;
    private TElementIdentifier _elementIdentifier_;
    private TElementOf _elementOf_;
    private PSetExpression _setExpression_;
    private TComma _comma_;
    private PExpression _expression_;

    public AForAllProposition()
    {
        // Constructor
    }

    public AForAllProposition(
        @SuppressWarnings("hiding") TForAll _forAll_,
        @SuppressWarnings("hiding") TElementIdentifier _elementIdentifier_,
        @SuppressWarnings("hiding") TElementOf _elementOf_,
        @SuppressWarnings("hiding") PSetExpression _setExpression_,
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PExpression _expression_)
    {
        // Constructor
        setForAll(_forAll_);

        setElementIdentifier(_elementIdentifier_);

        setElementOf(_elementOf_);

        setSetExpression(_setExpression_);

        setComma(_comma_);

        setExpression(_expression_);

    }

    @Override
    public Object clone()
    {
        return new AForAllProposition(
            cloneNode(this._forAll_),
            cloneNode(this._elementIdentifier_),
            cloneNode(this._elementOf_),
            cloneNode(this._setExpression_),
            cloneNode(this._comma_),
            cloneNode(this._expression_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAForAllProposition(this);
    }

    public TForAll getForAll()
    {
        return this._forAll_;
    }

    public void setForAll(TForAll node)
    {
        if(this._forAll_ != null)
        {
            this._forAll_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._forAll_ = node;
    }

    public TElementIdentifier getElementIdentifier()
    {
        return this._elementIdentifier_;
    }

    public void setElementIdentifier(TElementIdentifier node)
    {
        if(this._elementIdentifier_ != null)
        {
            this._elementIdentifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._elementIdentifier_ = node;
    }

    public TElementOf getElementOf()
    {
        return this._elementOf_;
    }

    public void setElementOf(TElementOf node)
    {
        if(this._elementOf_ != null)
        {
            this._elementOf_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._elementOf_ = node;
    }

    public PSetExpression getSetExpression()
    {
        return this._setExpression_;
    }

    public void setSetExpression(PSetExpression node)
    {
        if(this._setExpression_ != null)
        {
            this._setExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._setExpression_ = node;
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._forAll_)
            + toString(this._elementIdentifier_)
            + toString(this._elementOf_)
            + toString(this._setExpression_)
            + toString(this._comma_)
            + toString(this._expression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._forAll_ == child)
        {
            this._forAll_ = null;
            return;
        }

        if(this._elementIdentifier_ == child)
        {
            this._elementIdentifier_ = null;
            return;
        }

        if(this._elementOf_ == child)
        {
            this._elementOf_ = null;
            return;
        }

        if(this._setExpression_ == child)
        {
            this._setExpression_ = null;
            return;
        }

        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._forAll_ == oldChild)
        {
            setForAll((TForAll) newChild);
            return;
        }

        if(this._elementIdentifier_ == oldChild)
        {
            setElementIdentifier((TElementIdentifier) newChild);
            return;
        }

        if(this._elementOf_ == oldChild)
        {
            setElementOf((TElementOf) newChild);
            return;
        }

        if(this._setExpression_ == oldChild)
        {
            setSetExpression((PSetExpression) newChild);
            return;
        }

        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
