/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AGeometryProgram extends PProgram
{
    private TCategory _category_;
    private TGeometry _geometry_;
    private TSemicolon _semicolon_;

    public AGeometryProgram()
    {
        // Constructor
    }

    public AGeometryProgram(
        @SuppressWarnings("hiding") TCategory _category_,
        @SuppressWarnings("hiding") TGeometry _geometry_,
        @SuppressWarnings("hiding") TSemicolon _semicolon_)
    {
        // Constructor
        setCategory(_category_);

        setGeometry(_geometry_);

        setSemicolon(_semicolon_);

    }

    @Override
    public Object clone()
    {
        return new AGeometryProgram(
            cloneNode(this._category_),
            cloneNode(this._geometry_),
            cloneNode(this._semicolon_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGeometryProgram(this);
    }

    public TCategory getCategory()
    {
        return this._category_;
    }

    public void setCategory(TCategory node)
    {
        if(this._category_ != null)
        {
            this._category_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._category_ = node;
    }

    public TGeometry getGeometry()
    {
        return this._geometry_;
    }

    public void setGeometry(TGeometry node)
    {
        if(this._geometry_ != null)
        {
            this._geometry_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._geometry_ = node;
    }

    public TSemicolon getSemicolon()
    {
        return this._semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(this._semicolon_ != null)
        {
            this._semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semicolon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._category_)
            + toString(this._geometry_)
            + toString(this._semicolon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._category_ == child)
        {
            this._category_ = null;
            return;
        }

        if(this._geometry_ == child)
        {
            this._geometry_ = null;
            return;
        }

        if(this._semicolon_ == child)
        {
            this._semicolon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._category_ == oldChild)
        {
            setCategory((TCategory) newChild);
            return;
        }

        if(this._geometry_ == oldChild)
        {
            setGeometry((TGeometry) newChild);
            return;
        }

        if(this._semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
