/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AModuloElementFactor extends PElementFactor
{
    private PElementFactor _elementFactor_;
    private TModulo _modulo_;
    private PElementTerm _elementTerm_;

    public AModuloElementFactor()
    {
        // Constructor
    }

    public AModuloElementFactor(
        @SuppressWarnings("hiding") PElementFactor _elementFactor_,
        @SuppressWarnings("hiding") TModulo _modulo_,
        @SuppressWarnings("hiding") PElementTerm _elementTerm_)
    {
        // Constructor
        setElementFactor(_elementFactor_);

        setModulo(_modulo_);

        setElementTerm(_elementTerm_);

    }

    @Override
    public Object clone()
    {
        return new AModuloElementFactor(
            cloneNode(this._elementFactor_),
            cloneNode(this._modulo_),
            cloneNode(this._elementTerm_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAModuloElementFactor(this);
    }

    public PElementFactor getElementFactor()
    {
        return this._elementFactor_;
    }

    public void setElementFactor(PElementFactor node)
    {
        if(this._elementFactor_ != null)
        {
            this._elementFactor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._elementFactor_ = node;
    }

    public TModulo getModulo()
    {
        return this._modulo_;
    }

    public void setModulo(TModulo node)
    {
        if(this._modulo_ != null)
        {
            this._modulo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._modulo_ = node;
    }

    public PElementTerm getElementTerm()
    {
        return this._elementTerm_;
    }

    public void setElementTerm(PElementTerm node)
    {
        if(this._elementTerm_ != null)
        {
            this._elementTerm_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._elementTerm_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._elementFactor_)
            + toString(this._modulo_)
            + toString(this._elementTerm_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._elementFactor_ == child)
        {
            this._elementFactor_ = null;
            return;
        }

        if(this._modulo_ == child)
        {
            this._modulo_ = null;
            return;
        }

        if(this._elementTerm_ == child)
        {
            this._elementTerm_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._elementFactor_ == oldChild)
        {
            setElementFactor((PElementFactor) newChild);
            return;
        }

        if(this._modulo_ == oldChild)
        {
            setModulo((TModulo) newChild);
            return;
        }

        if(this._elementTerm_ == oldChild)
        {
            setElementTerm((PElementTerm) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
