/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ANeitherGreaterThanNorEqualToElementComparison extends PElementComparison
{
    private PElementComparison _elementComparison_;
    private TNeitherGreaterThanNorEqualTo _neitherGreaterThanNorEqualTo_;
    private PElementArithmetic _elementArithmetic_;

    public ANeitherGreaterThanNorEqualToElementComparison()
    {
        // Constructor
    }

    public ANeitherGreaterThanNorEqualToElementComparison(
        @SuppressWarnings("hiding") PElementComparison _elementComparison_,
        @SuppressWarnings("hiding") TNeitherGreaterThanNorEqualTo _neitherGreaterThanNorEqualTo_,
        @SuppressWarnings("hiding") PElementArithmetic _elementArithmetic_)
    {
        // Constructor
        setElementComparison(_elementComparison_);

        setNeitherGreaterThanNorEqualTo(_neitherGreaterThanNorEqualTo_);

        setElementArithmetic(_elementArithmetic_);

    }

    @Override
    public Object clone()
    {
        return new ANeitherGreaterThanNorEqualToElementComparison(
            cloneNode(this._elementComparison_),
            cloneNode(this._neitherGreaterThanNorEqualTo_),
            cloneNode(this._elementArithmetic_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANeitherGreaterThanNorEqualToElementComparison(this);
    }

    public PElementComparison getElementComparison()
    {
        return this._elementComparison_;
    }

    public void setElementComparison(PElementComparison node)
    {
        if(this._elementComparison_ != null)
        {
            this._elementComparison_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._elementComparison_ = node;
    }

    public TNeitherGreaterThanNorEqualTo getNeitherGreaterThanNorEqualTo()
    {
        return this._neitherGreaterThanNorEqualTo_;
    }

    public void setNeitherGreaterThanNorEqualTo(TNeitherGreaterThanNorEqualTo node)
    {
        if(this._neitherGreaterThanNorEqualTo_ != null)
        {
            this._neitherGreaterThanNorEqualTo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._neitherGreaterThanNorEqualTo_ = node;
    }

    public PElementArithmetic getElementArithmetic()
    {
        return this._elementArithmetic_;
    }

    public void setElementArithmetic(PElementArithmetic node)
    {
        if(this._elementArithmetic_ != null)
        {
            this._elementArithmetic_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._elementArithmetic_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._elementComparison_)
            + toString(this._neitherGreaterThanNorEqualTo_)
            + toString(this._elementArithmetic_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._elementComparison_ == child)
        {
            this._elementComparison_ = null;
            return;
        }

        if(this._neitherGreaterThanNorEqualTo_ == child)
        {
            this._neitherGreaterThanNorEqualTo_ = null;
            return;
        }

        if(this._elementArithmetic_ == child)
        {
            this._elementArithmetic_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._elementComparison_ == oldChild)
        {
            setElementComparison((PElementComparison) newChild);
            return;
        }

        if(this._neitherGreaterThanNorEqualTo_ == oldChild)
        {
            setNeitherGreaterThanNorEqualTo((TNeitherGreaterThanNorEqualTo) newChild);
            return;
        }

        if(this._elementArithmetic_ == oldChild)
        {
            setElementArithmetic((PElementArithmetic) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
