/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ANotASubsetOfSetComparison extends PSetComparison
{
    private PSetComparison _setComparison_;
    private TNotASubsetOf _notASubsetOf_;
    private PSetArithmetic _setArithmetic_;

    public ANotASubsetOfSetComparison()
    {
        // Constructor
    }

    public ANotASubsetOfSetComparison(
        @SuppressWarnings("hiding") PSetComparison _setComparison_,
        @SuppressWarnings("hiding") TNotASubsetOf _notASubsetOf_,
        @SuppressWarnings("hiding") PSetArithmetic _setArithmetic_)
    {
        // Constructor
        setSetComparison(_setComparison_);

        setNotASubsetOf(_notASubsetOf_);

        setSetArithmetic(_setArithmetic_);

    }

    @Override
    public Object clone()
    {
        return new ANotASubsetOfSetComparison(
            cloneNode(this._setComparison_),
            cloneNode(this._notASubsetOf_),
            cloneNode(this._setArithmetic_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotASubsetOfSetComparison(this);
    }

    public PSetComparison getSetComparison()
    {
        return this._setComparison_;
    }

    public void setSetComparison(PSetComparison node)
    {
        if(this._setComparison_ != null)
        {
            this._setComparison_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._setComparison_ = node;
    }

    public TNotASubsetOf getNotASubsetOf()
    {
        return this._notASubsetOf_;
    }

    public void setNotASubsetOf(TNotASubsetOf node)
    {
        if(this._notASubsetOf_ != null)
        {
            this._notASubsetOf_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._notASubsetOf_ = node;
    }

    public PSetArithmetic getSetArithmetic()
    {
        return this._setArithmetic_;
    }

    public void setSetArithmetic(PSetArithmetic node)
    {
        if(this._setArithmetic_ != null)
        {
            this._setArithmetic_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._setArithmetic_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._setComparison_)
            + toString(this._notASubsetOf_)
            + toString(this._setArithmetic_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._setComparison_ == child)
        {
            this._setComparison_ = null;
            return;
        }

        if(this._notASubsetOf_ == child)
        {
            this._notASubsetOf_ = null;
            return;
        }

        if(this._setArithmetic_ == child)
        {
            this._setArithmetic_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._setComparison_ == oldChild)
        {
            setSetComparison((PSetComparison) newChild);
            return;
        }

        if(this._notASubsetOf_ == oldChild)
        {
            setNotASubsetOf((TNotASubsetOf) newChild);
            return;
        }

        if(this._setArithmetic_ == oldChild)
        {
            setSetArithmetic((PSetArithmetic) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
