/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class APlusSetArithmetic extends PSetArithmetic
{
    private PSetArithmetic _setArithmetic_;
    private TPlus _plus_;
    private PSetFactor _setFactor_;

    public APlusSetArithmetic()
    {
        // Constructor
    }

    public APlusSetArithmetic(
        @SuppressWarnings("hiding") PSetArithmetic _setArithmetic_,
        @SuppressWarnings("hiding") TPlus _plus_,
        @SuppressWarnings("hiding") PSetFactor _setFactor_)
    {
        // Constructor
        setSetArithmetic(_setArithmetic_);

        setPlus(_plus_);

        setSetFactor(_setFactor_);

    }

    @Override
    public Object clone()
    {
        return new APlusSetArithmetic(
            cloneNode(this._setArithmetic_),
            cloneNode(this._plus_),
            cloneNode(this._setFactor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPlusSetArithmetic(this);
    }

    public PSetArithmetic getSetArithmetic()
    {
        return this._setArithmetic_;
    }

    public void setSetArithmetic(PSetArithmetic node)
    {
        if(this._setArithmetic_ != null)
        {
            this._setArithmetic_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._setArithmetic_ = node;
    }

    public TPlus getPlus()
    {
        return this._plus_;
    }

    public void setPlus(TPlus node)
    {
        if(this._plus_ != null)
        {
            this._plus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._plus_ = node;
    }

    public PSetFactor getSetFactor()
    {
        return this._setFactor_;
    }

    public void setSetFactor(PSetFactor node)
    {
        if(this._setFactor_ != null)
        {
            this._setFactor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._setFactor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._setArithmetic_)
            + toString(this._plus_)
            + toString(this._setFactor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._setArithmetic_ == child)
        {
            this._setArithmetic_ = null;
            return;
        }

        if(this._plus_ == child)
        {
            this._plus_ = null;
            return;
        }

        if(this._setFactor_ == child)
        {
            this._setFactor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._setArithmetic_ == oldChild)
        {
            setSetArithmetic((PSetArithmetic) newChild);
            return;
        }

        if(this._plus_ == oldChild)
        {
            setPlus((TPlus) newChild);
            return;
        }

        if(this._setFactor_ == oldChild)
        {
            setSetFactor((PSetFactor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
