/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AProofBlock extends PProofBlock
{
    private TProof _proof_;
    private TColumn _column_;
    private PProofInstructionList _proofInstructionList_;

    public AProofBlock()
    {
        // Constructor
    }

    public AProofBlock(
        @SuppressWarnings("hiding") TProof _proof_,
        @SuppressWarnings("hiding") TColumn _column_,
        @SuppressWarnings("hiding") PProofInstructionList _proofInstructionList_)
    {
        // Constructor
        setProof(_proof_);

        setColumn(_column_);

        setProofInstructionList(_proofInstructionList_);

    }

    @Override
    public Object clone()
    {
        return new AProofBlock(
            cloneNode(this._proof_),
            cloneNode(this._column_),
            cloneNode(this._proofInstructionList_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProofBlock(this);
    }

    public TProof getProof()
    {
        return this._proof_;
    }

    public void setProof(TProof node)
    {
        if(this._proof_ != null)
        {
            this._proof_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._proof_ = node;
    }

    public TColumn getColumn()
    {
        return this._column_;
    }

    public void setColumn(TColumn node)
    {
        if(this._column_ != null)
        {
            this._column_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._column_ = node;
    }

    public PProofInstructionList getProofInstructionList()
    {
        return this._proofInstructionList_;
    }

    public void setProofInstructionList(PProofInstructionList node)
    {
        if(this._proofInstructionList_ != null)
        {
            this._proofInstructionList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._proofInstructionList_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._proof_)
            + toString(this._column_)
            + toString(this._proofInstructionList_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._proof_ == child)
        {
            this._proof_ = null;
            return;
        }

        if(this._column_ == child)
        {
            this._column_ = null;
            return;
        }

        if(this._proofInstructionList_ == child)
        {
            this._proofInstructionList_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._proof_ == oldChild)
        {
            setProof((TProof) newChild);
            return;
        }

        if(this._column_ == oldChild)
        {
            setColumn((TColumn) newChild);
            return;
        }

        if(this._proofInstructionList_ == oldChild)
        {
            setProofInstructionList((PProofInstructionList) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
