/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ASetSetTerm extends PSetTerm
{
    private TSetIdentifier _setIdentifier_;

    public ASetSetTerm()
    {
        // Constructor
    }

    public ASetSetTerm(
        @SuppressWarnings("hiding") TSetIdentifier _setIdentifier_)
    {
        // Constructor
        setSetIdentifier(_setIdentifier_);

    }

    @Override
    public Object clone()
    {
        return new ASetSetTerm(
            cloneNode(this._setIdentifier_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASetSetTerm(this);
    }

    public TSetIdentifier getSetIdentifier()
    {
        return this._setIdentifier_;
    }

    public void setSetIdentifier(TSetIdentifier node)
    {
        if(this._setIdentifier_ != null)
        {
            this._setIdentifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._setIdentifier_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._setIdentifier_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._setIdentifier_ == child)
        {
            this._setIdentifier_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._setIdentifier_ == oldChild)
        {
            setSetIdentifier((TSetIdentifier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
