/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TAlgebra extends Token
{
    public TAlgebra()
    {
        super.setText("algebra");
    }

    public TAlgebra(int line, int pos)
    {
        super.setText("algebra");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAlgebra(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAlgebra(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAlgebra text.");
    }
}
