/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TAsk extends Token
{
    public TAsk()
    {
        super.setText("ask");
    }

    public TAsk(int line, int pos)
    {
        super.setText("ask");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAsk(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAsk(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAsk text.");
    }
}
