/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TElementOf extends Token
{
    public TElementOf()
    {
        super.setText("∈");
    }

    public TElementOf(int line, int pos)
    {
        super.setText("∈");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TElementOf(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTElementOf(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TElementOf text.");
    }
}
