/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TNotASupersetOf extends Token
{
    public TNotASupersetOf()
    {
        super.setText("⊅");
    }

    public TNotASupersetOf(int line, int pos)
    {
        super.setText("⊅");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TNotASupersetOf(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNotASupersetOf(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TNotASupersetOf text.");
    }
}
