/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TNotAnElementOf extends Token
{
    public TNotAnElementOf()
    {
        super.setText("∉");
    }

    public TNotAnElementOf(int line, int pos)
    {
        super.setText("∉");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TNotAnElementOf(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNotAnElementOf(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TNotAnElementOf text.");
    }
}
