/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TStatement extends Token
{
    public TStatement()
    {
        super.setText("statement");
    }

    public TStatement(int line, int pos)
    {
        super.setText("statement");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TStatement(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTStatement(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TStatement text.");
    }
}
