/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TStatisticAndProbability extends Token
{
    public TStatisticAndProbability()
    {
        super.setText("statistic and probability");
    }

    public TStatisticAndProbability(int line, int pos)
    {
        super.setText("statistic and probability");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TStatisticAndProbability(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTStatisticAndProbability(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TStatisticAndProbability text.");
    }
}
