/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TUnion extends Token
{
    public TUnion()
    {
        super.setText("∪");
    }

    public TUnion(int line, int pos)
    {
        super.setText("∪");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TUnion(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTUnion(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TUnion text.");
    }
}
